# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /root/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.8194.17/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /root/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.8194.17/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/CText

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/CText

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/root/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.8194.17/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/root/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.8194.17/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CText/CMakeFiles /root/CText/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CText/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CText

# Build rule for target.
CText: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CText
.PHONY : CText

# fast build rule for target.
CText/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/build
.PHONY : CText/fast

src/libs/image_manipulation/grayscale.o: src/libs/image_manipulation/grayscale.c.o

.PHONY : src/libs/image_manipulation/grayscale.o

# target to build an object file
src/libs/image_manipulation/grayscale.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/grayscale.c.o
.PHONY : src/libs/image_manipulation/grayscale.c.o

src/libs/image_manipulation/grayscale.i: src/libs/image_manipulation/grayscale.c.i

.PHONY : src/libs/image_manipulation/grayscale.i

# target to preprocess a source file
src/libs/image_manipulation/grayscale.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/grayscale.c.i
.PHONY : src/libs/image_manipulation/grayscale.c.i

src/libs/image_manipulation/grayscale.s: src/libs/image_manipulation/grayscale.c.s

.PHONY : src/libs/image_manipulation/grayscale.s

# target to generate assembly for a file
src/libs/image_manipulation/grayscale.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/grayscale.c.s
.PHONY : src/libs/image_manipulation/grayscale.c.s

src/libs/image_manipulation/otsu.o: src/libs/image_manipulation/otsu.c.o

.PHONY : src/libs/image_manipulation/otsu.o

# target to build an object file
src/libs/image_manipulation/otsu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/otsu.c.o
.PHONY : src/libs/image_manipulation/otsu.c.o

src/libs/image_manipulation/otsu.i: src/libs/image_manipulation/otsu.c.i

.PHONY : src/libs/image_manipulation/otsu.i

# target to preprocess a source file
src/libs/image_manipulation/otsu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/otsu.c.i
.PHONY : src/libs/image_manipulation/otsu.c.i

src/libs/image_manipulation/otsu.s: src/libs/image_manipulation/otsu.c.s

.PHONY : src/libs/image_manipulation/otsu.s

# target to generate assembly for a file
src/libs/image_manipulation/otsu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/otsu.c.s
.PHONY : src/libs/image_manipulation/otsu.c.s

src/libs/image_manipulation/pixel_operations.o: src/libs/image_manipulation/pixel_operations.c.o

.PHONY : src/libs/image_manipulation/pixel_operations.o

# target to build an object file
src/libs/image_manipulation/pixel_operations.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/pixel_operations.c.o
.PHONY : src/libs/image_manipulation/pixel_operations.c.o

src/libs/image_manipulation/pixel_operations.i: src/libs/image_manipulation/pixel_operations.c.i

.PHONY : src/libs/image_manipulation/pixel_operations.i

# target to preprocess a source file
src/libs/image_manipulation/pixel_operations.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/pixel_operations.c.i
.PHONY : src/libs/image_manipulation/pixel_operations.c.i

src/libs/image_manipulation/pixel_operations.s: src/libs/image_manipulation/pixel_operations.c.s

.PHONY : src/libs/image_manipulation/pixel_operations.s

# target to generate assembly for a file
src/libs/image_manipulation/pixel_operations.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/pixel_operations.c.s
.PHONY : src/libs/image_manipulation/pixel_operations.c.s

src/libs/image_manipulation/segmentation.o: src/libs/image_manipulation/segmentation.c.o

.PHONY : src/libs/image_manipulation/segmentation.o

# target to build an object file
src/libs/image_manipulation/segmentation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/segmentation.c.o
.PHONY : src/libs/image_manipulation/segmentation.c.o

src/libs/image_manipulation/segmentation.i: src/libs/image_manipulation/segmentation.c.i

.PHONY : src/libs/image_manipulation/segmentation.i

# target to preprocess a source file
src/libs/image_manipulation/segmentation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/segmentation.c.i
.PHONY : src/libs/image_manipulation/segmentation.c.i

src/libs/image_manipulation/segmentation.s: src/libs/image_manipulation/segmentation.c.s

.PHONY : src/libs/image_manipulation/segmentation.s

# target to generate assembly for a file
src/libs/image_manipulation/segmentation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/image_manipulation/segmentation.c.s
.PHONY : src/libs/image_manipulation/segmentation.c.s

src/libs/list/list.o: src/libs/list/list.c.o

.PHONY : src/libs/list/list.o

# target to build an object file
src/libs/list/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/list/list.c.o
.PHONY : src/libs/list/list.c.o

src/libs/list/list.i: src/libs/list/list.c.i

.PHONY : src/libs/list/list.i

# target to preprocess a source file
src/libs/list/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/list/list.c.i
.PHONY : src/libs/list/list.c.i

src/libs/list/list.s: src/libs/list/list.c.s

.PHONY : src/libs/list/list.s

# target to generate assembly for a file
src/libs/list/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/list/list.c.s
.PHONY : src/libs/list/list.c.s

src/libs/neural_network/neuralnetwork.o: src/libs/neural_network/neuralnetwork.c.o

.PHONY : src/libs/neural_network/neuralnetwork.o

# target to build an object file
src/libs/neural_network/neuralnetwork.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/neural_network/neuralnetwork.c.o
.PHONY : src/libs/neural_network/neuralnetwork.c.o

src/libs/neural_network/neuralnetwork.i: src/libs/neural_network/neuralnetwork.c.i

.PHONY : src/libs/neural_network/neuralnetwork.i

# target to preprocess a source file
src/libs/neural_network/neuralnetwork.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/neural_network/neuralnetwork.c.i
.PHONY : src/libs/neural_network/neuralnetwork.c.i

src/libs/neural_network/neuralnetwork.s: src/libs/neural_network/neuralnetwork.c.s

.PHONY : src/libs/neural_network/neuralnetwork.s

# target to generate assembly for a file
src/libs/neural_network/neuralnetwork.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/neural_network/neuralnetwork.c.s
.PHONY : src/libs/neural_network/neuralnetwork.c.s

src/libs/neural_network/neuron.o: src/libs/neural_network/neuron.c.o

.PHONY : src/libs/neural_network/neuron.o

# target to build an object file
src/libs/neural_network/neuron.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/neural_network/neuron.c.o
.PHONY : src/libs/neural_network/neuron.c.o

src/libs/neural_network/neuron.i: src/libs/neural_network/neuron.c.i

.PHONY : src/libs/neural_network/neuron.i

# target to preprocess a source file
src/libs/neural_network/neuron.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/neural_network/neuron.c.i
.PHONY : src/libs/neural_network/neuron.c.i

src/libs/neural_network/neuron.s: src/libs/neural_network/neuron.c.s

.PHONY : src/libs/neural_network/neuron.s

# target to generate assembly for a file
src/libs/neural_network/neuron.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/libs/neural_network/neuron.c.s
.PHONY : src/libs/neural_network/neuron.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CText.dir/build.make CMakeFiles/CText.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CText"
	@echo "... src/libs/image_manipulation/grayscale.o"
	@echo "... src/libs/image_manipulation/grayscale.i"
	@echo "... src/libs/image_manipulation/grayscale.s"
	@echo "... src/libs/image_manipulation/otsu.o"
	@echo "... src/libs/image_manipulation/otsu.i"
	@echo "... src/libs/image_manipulation/otsu.s"
	@echo "... src/libs/image_manipulation/pixel_operations.o"
	@echo "... src/libs/image_manipulation/pixel_operations.i"
	@echo "... src/libs/image_manipulation/pixel_operations.s"
	@echo "... src/libs/image_manipulation/segmentation.o"
	@echo "... src/libs/image_manipulation/segmentation.i"
	@echo "... src/libs/image_manipulation/segmentation.s"
	@echo "... src/libs/list/list.o"
	@echo "... src/libs/list/list.i"
	@echo "... src/libs/list/list.s"
	@echo "... src/libs/neural_network/neuralnetwork.o"
	@echo "... src/libs/neural_network/neuralnetwork.i"
	@echo "... src/libs/neural_network/neuralnetwork.s"
	@echo "... src/libs/neural_network/neuron.o"
	@echo "... src/libs/neural_network/neuron.i"
	@echo "... src/libs/neural_network/neuron.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

