name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update -y -qq
        sudo apt install libsdl1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libgtk-3-dev
    - name: Make the projet
      run: make
