name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update -y -qq
        sudo apt install libsdl libsdl2 libsdl2-image
    - name: CMake the project
      run: cmake .
    - name: Make the projet
      run: make
